import Link from 'next/link';
import './globals.css';
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'React HOCs example',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <header>
          <Link href='/'>Home</Link>
          <Link href='/profile'>Profile</Link>
          <Link href='/todos'>Todos</Link>
        </header>
        {children}
      </body>
    </html>
  );
}
